import Head from 'next/head'
import { AboutDetails } from '../../components'

export default function About() {
  return (
    <>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{height: '100%'}}>
        <AboutDetails />
      </main>
    </>
  )
}
